name: day1 problem 5

on:
    push:
        branches:
            - main
        paths:
            - 'day-01/src/**'
        
    pull_request:
        branches:
            - main
        paths:
            - 'day-01/src/**'
   

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v4
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
            - name: Run tests
              run: |
                pip --version
                python --version
