name: Day1 Problem 6

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    print:
        runs-on: ubuntu-latest

        steps:
        - name: Print All envrionment variables
          run: |
            - echo "Event name: ${{ github.event_name }}"
            - echo "Repository: ${{ github.repository }}"
            - echo "Actor: ${{ github.actor }}"
            - echo "Workflow: ${{ github.workflow }}"
            - echo "Job: ${{ github.job }}"
            - echo "Ref: ${{ github.ref }}"