name: day2 problem 2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: build job
          run: echo "hello world"

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
        - name: deploy job
          run: echo "deploying to production"